config/routes.rb
AddressBook::Application.routes.draw do
  resources :contacts

  get "home/index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
	attr_accessible :first_name, :last_name, :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :contacts
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorized_user, :only => [:show, :destroy, :edit, :update]

  # GET /contacts
  def index
    @user = current_user
    @contacts = @user.contacts
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contacts }
    end
  end

  # GET /contacts/1
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new if signed_in?
    unless params[:id].nil?
      @contact = Contact.find(params[:id])
      @contact.user_id = current_user
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # POST /contacts
  def create
    @contact = current_user.contacts.build(params[:contact])
    respond_to do |format|
      if @contact.save
        format.html { redirect_to(@contact, :notice => 'Contact was successfully created.') }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # PUT /contacts/1
  def update
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'Contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end

  # Prevent users from viewing/modifying other user's contacts if id is known.
  def authorized_user
    if current_user.try(:admin?) #if admin they are allowed to modify any user's contact
      @contact = Contact.find(params[:id])
    else
      @contact = current_user.contacts.find_by_id(params[:id])
    end
    redirect_to contacts_path if @contact.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorized_admin, :only => [:index]
  before_filter :authorized_user, :only => [:show]

  # GET /users
  def index
  	@users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/edit
  def edit
    @user = current_user
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  # Only admin can view all users.
  def authorized_admin
    unless current_user.try(:admin?)
      redirect_to(current_user, :notice => 'That page is protected.')
    end
  end

  # Prevent users from viewing/modifying other users if id is known.
  def authorized_user
    if current_user.try(:admin?) #if admin they are allowed to modify any user's data
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    redirect_to root_path if @user.nil?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.phone %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Delete', contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @contact.phone %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h1>Home</h1>

<p>Total Users:  <%=@users.count %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Admin</th>
  </tr>
<% @users.each do |user| %>
  <tr>
  	<td><%=link_to user.name, user %></td>
  	<td><%=user.admin? ? 'yes' : 'no' %>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Address Book</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Home", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Contacts", contacts_path %></li>
              <li><%= link_to "Admin", users_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="notice" />
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Admin</h1>
<br />
<ul class="users">
	<% @users.each do |user| %>
    <li>
      Name: <%=link_to user.name, user %> <br />
      Email: <%=user.email %> <br />
      Created: <%=user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p> Email: <%= @user.email if @user.email %> </p>
<p> Total Contacts: <%= @user.contacts.count %></p>
<%=link_to 'View Contacts', contacts_path %> <br />